dataset:
  root: data/
  train_part: 0.95
  name: vlsp2019_train_set # custom name
  sample_rate: 22050
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 4
  batch_size: 8
  clip_grad_norm: 3
  epochs: 500
  optimizer:
    lr: 0.0001 # 0.0003 
    weight_decay: 0.0001 # leave default
  from_checkpoint: checkpoints/best.pth

wandb:
  project: Vietnamsese Speech Recognition
  log_interval: 20
model:
  name: _quartznet5x5_config
  vocab_size: 150
  feat_in: 64

